# theme: minima
theme: jekyll-clean-dark

# minima:
#   skin: dark

lsi: false
safe: true
source: [https://github.com/SodiKroehler/SodiKroehler.github.io]
incremental: false
markdown: GFM
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge