# theme: minima
theme: jekyll-theme-cayman

remote_theme: broccolini/swiss
minima:
  skin: dark

title: "Sodi Kroehler"
description: "Personal Website"
lsi: false
safe: true
source: [https://github.com/SodiKroehler/SodiKroehler.github.io]
show_downloads: true
incremental: false
markdown: GFM
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme_color: black