

title: "Sodi Kroehler"
theme: jekyll-theme-midnight 
markdown: kramdown
highlighter: rouge


plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      permalink: pretty
